################################################################################
#
# chicken_scheme
#
################################################################################

CHICKEN_SCHEME_VERSION = 5.1.0
CHICKEN_SCHEME_SOURCE = chicken-$(CHICKEN_SCHEME_VERSION).tar.gz
CHICKEN_SCHEME_SITE = https://code.call-cc.org/releases/${CHICKEN_SCHEME_VERSION}
CHICKEN_SCHEME_LICENSE = BSD
CHICKEN_SCHEME_LICENSE_FILES = LICENSE
CHICKEN_SCHEME_INSTALL_STAGING=YES
CHICKEN_SCHEME_INSTALL_TARGET=YES
HOST_CHICKEN_SCHEME_INSTALL_HOST=YES

CHICKEN_SCHEME_MAKE_ARGS=ARCH= PREFIX=/usr PLATFORM=linux HOSTSYSTEM=${GNU_TARGET_NAME} TARGET_FEATURES="-no-feature x86 -feature arm -feature aarch64"
HOST_CHICKEN_SCHEME_MAKE_ARGS=PREFIX=${HOST_DIR} PLATFORM=linux TARGETSYSTEM=${GNU_TARGET_NAME} TARGET_PREFIX=${TARGET_DIR} TARGET_RUN_PREFIX=/usr PROGRAM_PREFIX=aarch64-

HOST_CHICKEN_SCHEME_DEPENDENCIES = chicken-scheme

define CHICKEN_SCHEME_CONFIGURE_CMDS
	$(TARGET_MAKE_ENV) $(MAKE1) -C $(@D) PLATFORM=linux confclean
endef

define HOST_CHICKEN_SCHEME_CONFIGURE_CMDS
	$(HOST_MAKE_ENV) $(MAKE1) -C $(@D) PLATFORM=linux confclean
endef

define CHICKEN_SCHEME_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(MAKE1) -C $(@D) ${CHICKEN_SCHEME_MAKE_ARGS}
endef

define HOST_CHICKEN_SCHEME_BUILD_CMDS
	$(HOST_MAKE_ENV) $(MAKE1) -C $(@D) ${HOST_CHICKEN_SCHEME_MAKE_ARGS}
endef

define CHICKEN_SCHEME_INSTALL_STAGING_CMDS
	$(TARGET_MAKE_ENV) $(MAKE1) -C $(@D) ${CHICKEN_SCHEME_MAKE_ARGS} DESTDIR="$(STAGING_DIR)" install
endef

define CHICKEN_SCHEME_INSTALL_TARGET_CMDS
	$(TARGET_MAKE_ENV) $(MAKE1) -C $(@D) ${CHICKEN_SCHEME_MAKE_ARGS} DESTDIR="$(TARGET_DIR)" install-target install-bin
endef

define HOST_CHICKEN_SCHEME_INSTALL_CMDS
	$(HOST_MAKE_ENV) $(MAKE1) -C $(@D) ${HOST_CHICKEN_SCHEME_MAKE_ARGS} install
endef 

$(eval $(generic-package))
$(eval $(host-generic-package))
